DROP TABLE IF EXISTS `users`;

CREATE TABLE `users`  (
  `id` BIGINT AUTO_INCREMENT  PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(400) NOT NULL
);